import { Router } from "express";
import authRoutes from "./auth.routes";
import userRoutes from "./user.routes";
import categoryRoutes from "./category.routes";
import productRoutes from "./product.routes";
import orderRoutes from "./order.routes";
import reviewRoutes from "./review.routes";
import attendanceRoutes from "./attendance.routes";
import leaveRoutes from "./leave.routes";
import taskRoutes from "./task.routes";
import performanceRoutes from "./performance.routes";
import salaryRoutes from "./salary.routes";
import inventoryRoutes from "./inventory.routes";
import reportRoutes from "./report.routes";
import heroSlideRoutes from "./heroSlide.routes";
import homepageSectionRoutes from "./homepageSection.routes";
import siteSettingsRoutes from "./siteSettings.routes";
import couponRoutes from "./coupon.routes";
import navLinkRoutes from "./navLink.routes";
import footerColumnRoutes from "./footerColumn.routes";
import staticPageRoutes from "./staticPage.routes";
import auditLogRoutes from "./auditLog.routes";
import pendingActionRoutes from "./pendingAction.routes";
import approvalSettingsRoutes from "./approvalSettings.routes";
import investmentRoutes from "./investment.routes";
import expenseRoutes from "./expense.routes";
import refundRoutes from "./refund.routes";
import financeRoutes from "./finance.routes";
import roleRoutes from "./role.routes";
import shopRoutes from "./shop.routes";
import purchaseRoutes from "./purchase.routes";
import campaignRoutes from "./campaign.routes";
import notificationRoutes from "./notification.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/categories", categoryRoutes);
router.use("/products", productRoutes);
router.use("/orders", orderRoutes);
router.use("/reviews", reviewRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/leaves", leaveRoutes);
router.use("/tasks", taskRoutes);
router.use("/performance-reviews", performanceRoutes);
router.use("/salary-payments", salaryRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/reports", reportRoutes);
router.use("/hero-slides", heroSlideRoutes);
router.use("/homepage-sections", homepageSectionRoutes);
router.use("/site-settings", siteSettingsRoutes);
router.use("/coupons", couponRoutes);
router.use("/nav-links", navLinkRoutes);
router.use("/footer-columns", footerColumnRoutes);
router.use("/static-pages", staticPageRoutes);
router.use("/audit-logs", auditLogRoutes);
router.use("/pending-actions", pendingActionRoutes);
router.use("/approval-settings", approvalSettingsRoutes);
router.use("/investments", investmentRoutes);
router.use("/expenses", expenseRoutes);
router.use("/refunds", refundRoutes);
router.use("/finance", financeRoutes);
router.use("/roles", roleRoutes);
router.use("/shops", shopRoutes);
router.use("/purchases", purchaseRoutes);
router.use("/campaigns", campaignRoutes);
router.use("/notifications", notificationRoutes);

export default router;
