/**
 * Curated local photography, matched to a specific date variety / category.
 *
 * These are a *fallback* only — a real Cloudinary photo uploaded through the
 * admin portal always wins (see `lib/mappers.ts`). They exist so the seeded
 * catalogue renders real product photography instead of the decorative
 * `<ProductVisual>` gradient.
 *
 * Entries are keyed by the variety the photo actually shows. Never point a
 * slug at a photo of a different variety — a customer buying Ajwa must not be
 * shown a picture of Mariyam dates. A product with no matching photo keeps the
 * gradient fallback until real photography is uploaded.
 */

/** Product slug (as seeded/generated by the backend) -> local photo. */
const PRODUCT_PHOTOS: Record<string, string> = {
  "mabroom-dates-premium-saudi": "/images/products/mabroom-dates.webp",
  "sukkari-dates-golden-saudi": "/images/products/sukkari-dates.webp",
};

/** Category slug -> local photo. */
const CATEGORY_PHOTOS: Record<string, string> = {
  dates: "/images/categories/dates.webp",
};

export function getProductPhoto(slug: string): string | undefined {
  return PRODUCT_PHOTOS[slug];
}

export function getCategoryPhoto(slug: string): string | undefined {
  return CATEGORY_PHOTOS[slug];
}
